export type SupportedNetworkId =
  | '1'
  | '3'
  | '4'
  | '5'
  | '314'
  | '3141'
  | '1337'
  | '31337'

export type ContractName =
  | 'BaseRegistrarImplementation'
  | 'RegistrarController'
  | 'Multicall'
  | 'NameWrapper'
  | 'DNSRegistrar'
  | 'PublicResolver'
  | 'Registry'
  | 'ReverseRegistrar'
  | 'UniversalResolver'
  | 'BulkRenewal'
  | 'DNSSECImpl'
  | 'P256SHA256Algorithm'
  | 'RSASHA256Algorithm'
  | 'SHA1Digest'
  | 'Sunday'
  | 'Receiver'
  | 'SHA256Digest'
  | 'TLDPublicSuffixList'
  | 'FNSToken'
  | 'OffchainDNSResolver'
  | 'RSASHA1Algorithm'
  | 'Root'
  | 'StaticMetadataService'
  | 'TestRegistrar'
